//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileSignatureClient.SignatureServiceStub {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/webservices", ConfigurationName="SignatureServiceStub.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name phoneNumber from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/setCertificateInitials", ReplyAction="*")]
        MobileSignatureClient.SignatureServiceStub.setCertificateInitialsResponse setCertificateInitials(MobileSignatureClient.SignatureServiceStub.setCertificateInitialsRequest request);
        
        // CODEGEN: Generating message contract since element name hashForSign64 from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/SignHash", ReplyAction="*")]
        MobileSignatureClient.SignatureServiceStub.SignHashResponse SignHash(MobileSignatureClient.SignatureServiceStub.SignHashRequest request);
        
        // CODEGEN: Generating message contract since element name getSigningCertResult from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getSigningCert", ReplyAction="*")]
        MobileSignatureClient.SignatureServiceStub.getSigningCertResponse getSigningCert(MobileSignatureClient.SignatureServiceStub.getSigningCertRequest request);
        
        // CODEGEN: Generating message contract since element name getSigningCertAttrResult from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getSigningCertAttr", ReplyAction="*")]
        MobileSignatureClient.SignatureServiceStub.getSigningCertAttrResponse getSigningCertAttr(MobileSignatureClient.SignatureServiceStub.getSigningCertAttrRequest request);
        
        // CODEGEN: Generating message contract since element name getSigningCertAttrv2Result from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getSigningCertAttrv2", ReplyAction="*")]
        MobileSignatureClient.SignatureServiceStub.getSigningCertAttrv2Response getSigningCertAttrv2(MobileSignatureClient.SignatureServiceStub.getSigningCertAttrv2Request request);
        
        // CODEGEN: Generating message contract since element name getSignerIdentifierResult from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getSignerIdentifier", ReplyAction="*")]
        MobileSignatureClient.SignatureServiceStub.getSignerIdentifierResponse getSignerIdentifier(MobileSignatureClient.SignatureServiceStub.getSignerIdentifierRequest request);
        
        // CODEGEN: Generating message contract since element name getDigestAlgResult from namespace http://localhost/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/webservices/getDigestAlg", ReplyAction="*")]
        MobileSignatureClient.SignatureServiceStub.getDigestAlgResponse getDigestAlg(MobileSignatureClient.SignatureServiceStub.getDigestAlgRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCertificateInitialsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCertificateInitials", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.setCertificateInitialsRequestBody Body;
        
        public setCertificateInitialsRequest() {
        }
        
        public setCertificateInitialsRequest(MobileSignatureClient.SignatureServiceStub.setCertificateInitialsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class setCertificateInitialsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iOperator;
        
        public setCertificateInitialsRequestBody() {
        }
        
        public setCertificateInitialsRequestBody(string phoneNumber, int iOperator) {
            this.phoneNumber = phoneNumber;
            this.iOperator = iOperator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCertificateInitialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCertificateInitialsResponse", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.setCertificateInitialsResponseBody Body;
        
        public setCertificateInitialsResponse() {
        }
        
        public setCertificateInitialsResponse(MobileSignatureClient.SignatureServiceStub.setCertificateInitialsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class setCertificateInitialsResponseBody {
        
        public setCertificateInitialsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignHashRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignHash", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.SignHashRequestBody Body;
        
        public SignHashRequest() {
        }
        
        public SignHashRequest(MobileSignatureClient.SignatureServiceStub.SignHashRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class SignHashRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hashForSign64;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string displayText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int iOperator;
        
        public SignHashRequestBody() {
        }
        
        public SignHashRequestBody(string hashForSign64, string displayText, string phoneNumber, int iOperator) {
            this.hashForSign64 = hashForSign64;
            this.displayText = displayText;
            this.phoneNumber = phoneNumber;
            this.iOperator = iOperator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignHashResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignHashResponse", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.SignHashResponseBody Body;
        
        public SignHashResponse() {
        }
        
        public SignHashResponse(MobileSignatureClient.SignatureServiceStub.SignHashResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class SignHashResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SignHashResult;
        
        public SignHashResponseBody() {
        }
        
        public SignHashResponseBody(string SignHashResult) {
            this.SignHashResult = SignHashResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSigningCertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSigningCert", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.getSigningCertRequestBody Body;
        
        public getSigningCertRequest() {
        }
        
        public getSigningCertRequest(MobileSignatureClient.SignatureServiceStub.getSigningCertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getSigningCertRequestBody {
        
        public getSigningCertRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSigningCertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSigningCertResponse", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.getSigningCertResponseBody Body;
        
        public getSigningCertResponse() {
        }
        
        public getSigningCertResponse(MobileSignatureClient.SignatureServiceStub.getSigningCertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class getSigningCertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getSigningCertResult;
        
        public getSigningCertResponseBody() {
        }
        
        public getSigningCertResponseBody(string getSigningCertResult) {
            this.getSigningCertResult = getSigningCertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSigningCertAttrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSigningCertAttr", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.getSigningCertAttrRequestBody Body;
        
        public getSigningCertAttrRequest() {
        }
        
        public getSigningCertAttrRequest(MobileSignatureClient.SignatureServiceStub.getSigningCertAttrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getSigningCertAttrRequestBody {
        
        public getSigningCertAttrRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSigningCertAttrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSigningCertAttrResponse", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.getSigningCertAttrResponseBody Body;
        
        public getSigningCertAttrResponse() {
        }
        
        public getSigningCertAttrResponse(MobileSignatureClient.SignatureServiceStub.getSigningCertAttrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class getSigningCertAttrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getSigningCertAttrResult;
        
        public getSigningCertAttrResponseBody() {
        }
        
        public getSigningCertAttrResponseBody(string getSigningCertAttrResult) {
            this.getSigningCertAttrResult = getSigningCertAttrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSigningCertAttrv2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSigningCertAttrv2", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.getSigningCertAttrv2RequestBody Body;
        
        public getSigningCertAttrv2Request() {
        }
        
        public getSigningCertAttrv2Request(MobileSignatureClient.SignatureServiceStub.getSigningCertAttrv2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getSigningCertAttrv2RequestBody {
        
        public getSigningCertAttrv2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSigningCertAttrv2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSigningCertAttrv2Response", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.getSigningCertAttrv2ResponseBody Body;
        
        public getSigningCertAttrv2Response() {
        }
        
        public getSigningCertAttrv2Response(MobileSignatureClient.SignatureServiceStub.getSigningCertAttrv2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class getSigningCertAttrv2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getSigningCertAttrv2Result;
        
        public getSigningCertAttrv2ResponseBody() {
        }
        
        public getSigningCertAttrv2ResponseBody(string getSigningCertAttrv2Result) {
            this.getSigningCertAttrv2Result = getSigningCertAttrv2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSignerIdentifierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSignerIdentifier", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.getSignerIdentifierRequestBody Body;
        
        public getSignerIdentifierRequest() {
        }
        
        public getSignerIdentifierRequest(MobileSignatureClient.SignatureServiceStub.getSignerIdentifierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getSignerIdentifierRequestBody {
        
        public getSignerIdentifierRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSignerIdentifierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSignerIdentifierResponse", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.getSignerIdentifierResponseBody Body;
        
        public getSignerIdentifierResponse() {
        }
        
        public getSignerIdentifierResponse(MobileSignatureClient.SignatureServiceStub.getSignerIdentifierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class getSignerIdentifierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getSignerIdentifierResult;
        
        public getSignerIdentifierResponseBody() {
        }
        
        public getSignerIdentifierResponseBody(string getSignerIdentifierResult) {
            this.getSignerIdentifierResult = getSignerIdentifierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDigestAlgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDigestAlg", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.getDigestAlgRequestBody Body;
        
        public getDigestAlgRequest() {
        }
        
        public getDigestAlgRequest(MobileSignatureClient.SignatureServiceStub.getDigestAlgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getDigestAlgRequestBody {
        
        public getDigestAlgRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDigestAlgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDigestAlgResponse", Namespace="http://localhost/webservices", Order=0)]
        public MobileSignatureClient.SignatureServiceStub.getDigestAlgResponseBody Body;
        
        public getDigestAlgResponse() {
        }
        
        public getDigestAlgResponse(MobileSignatureClient.SignatureServiceStub.getDigestAlgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/webservices")]
    public partial class getDigestAlgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDigestAlgResult;
        
        public getDigestAlgResponseBody() {
        }
        
        public getDigestAlgResponseBody(string getDigestAlgResult) {
            this.getDigestAlgResult = getDigestAlgResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : MobileSignatureClient.SignatureServiceStub.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<MobileSignatureClient.SignatureServiceStub.Service1Soap>, MobileSignatureClient.SignatureServiceStub.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileSignatureClient.SignatureServiceStub.setCertificateInitialsResponse MobileSignatureClient.SignatureServiceStub.Service1Soap.setCertificateInitials(MobileSignatureClient.SignatureServiceStub.setCertificateInitialsRequest request) {
            return base.Channel.setCertificateInitials(request);
        }
        
        public void setCertificateInitials(string phoneNumber, int iOperator) {
            MobileSignatureClient.SignatureServiceStub.setCertificateInitialsRequest inValue = new MobileSignatureClient.SignatureServiceStub.setCertificateInitialsRequest();
            inValue.Body = new MobileSignatureClient.SignatureServiceStub.setCertificateInitialsRequestBody();
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.iOperator = iOperator;
            MobileSignatureClient.SignatureServiceStub.setCertificateInitialsResponse retVal = ((MobileSignatureClient.SignatureServiceStub.Service1Soap)(this)).setCertificateInitials(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileSignatureClient.SignatureServiceStub.SignHashResponse MobileSignatureClient.SignatureServiceStub.Service1Soap.SignHash(MobileSignatureClient.SignatureServiceStub.SignHashRequest request) {
            return base.Channel.SignHash(request);
        }
        
        public string SignHash(string hashForSign64, string displayText, string phoneNumber, int iOperator) {
            MobileSignatureClient.SignatureServiceStub.SignHashRequest inValue = new MobileSignatureClient.SignatureServiceStub.SignHashRequest();
            inValue.Body = new MobileSignatureClient.SignatureServiceStub.SignHashRequestBody();
            inValue.Body.hashForSign64 = hashForSign64;
            inValue.Body.displayText = displayText;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.iOperator = iOperator;
            MobileSignatureClient.SignatureServiceStub.SignHashResponse retVal = ((MobileSignatureClient.SignatureServiceStub.Service1Soap)(this)).SignHash(inValue);
            return retVal.Body.SignHashResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileSignatureClient.SignatureServiceStub.getSigningCertResponse MobileSignatureClient.SignatureServiceStub.Service1Soap.getSigningCert(MobileSignatureClient.SignatureServiceStub.getSigningCertRequest request) {
            return base.Channel.getSigningCert(request);
        }
        
        public string getSigningCert() {
            MobileSignatureClient.SignatureServiceStub.getSigningCertRequest inValue = new MobileSignatureClient.SignatureServiceStub.getSigningCertRequest();
            inValue.Body = new MobileSignatureClient.SignatureServiceStub.getSigningCertRequestBody();
            MobileSignatureClient.SignatureServiceStub.getSigningCertResponse retVal = ((MobileSignatureClient.SignatureServiceStub.Service1Soap)(this)).getSigningCert(inValue);
            return retVal.Body.getSigningCertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileSignatureClient.SignatureServiceStub.getSigningCertAttrResponse MobileSignatureClient.SignatureServiceStub.Service1Soap.getSigningCertAttr(MobileSignatureClient.SignatureServiceStub.getSigningCertAttrRequest request) {
            return base.Channel.getSigningCertAttr(request);
        }
        
        public string getSigningCertAttr() {
            MobileSignatureClient.SignatureServiceStub.getSigningCertAttrRequest inValue = new MobileSignatureClient.SignatureServiceStub.getSigningCertAttrRequest();
            inValue.Body = new MobileSignatureClient.SignatureServiceStub.getSigningCertAttrRequestBody();
            MobileSignatureClient.SignatureServiceStub.getSigningCertAttrResponse retVal = ((MobileSignatureClient.SignatureServiceStub.Service1Soap)(this)).getSigningCertAttr(inValue);
            return retVal.Body.getSigningCertAttrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileSignatureClient.SignatureServiceStub.getSigningCertAttrv2Response MobileSignatureClient.SignatureServiceStub.Service1Soap.getSigningCertAttrv2(MobileSignatureClient.SignatureServiceStub.getSigningCertAttrv2Request request) {
            return base.Channel.getSigningCertAttrv2(request);
        }
        
        public string getSigningCertAttrv2() {
            MobileSignatureClient.SignatureServiceStub.getSigningCertAttrv2Request inValue = new MobileSignatureClient.SignatureServiceStub.getSigningCertAttrv2Request();
            inValue.Body = new MobileSignatureClient.SignatureServiceStub.getSigningCertAttrv2RequestBody();
            MobileSignatureClient.SignatureServiceStub.getSigningCertAttrv2Response retVal = ((MobileSignatureClient.SignatureServiceStub.Service1Soap)(this)).getSigningCertAttrv2(inValue);
            return retVal.Body.getSigningCertAttrv2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileSignatureClient.SignatureServiceStub.getSignerIdentifierResponse MobileSignatureClient.SignatureServiceStub.Service1Soap.getSignerIdentifier(MobileSignatureClient.SignatureServiceStub.getSignerIdentifierRequest request) {
            return base.Channel.getSignerIdentifier(request);
        }
        
        public string getSignerIdentifier() {
            MobileSignatureClient.SignatureServiceStub.getSignerIdentifierRequest inValue = new MobileSignatureClient.SignatureServiceStub.getSignerIdentifierRequest();
            inValue.Body = new MobileSignatureClient.SignatureServiceStub.getSignerIdentifierRequestBody();
            MobileSignatureClient.SignatureServiceStub.getSignerIdentifierResponse retVal = ((MobileSignatureClient.SignatureServiceStub.Service1Soap)(this)).getSignerIdentifier(inValue);
            return retVal.Body.getSignerIdentifierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileSignatureClient.SignatureServiceStub.getDigestAlgResponse MobileSignatureClient.SignatureServiceStub.Service1Soap.getDigestAlg(MobileSignatureClient.SignatureServiceStub.getDigestAlgRequest request) {
            return base.Channel.getDigestAlg(request);
        }
        
        public string getDigestAlg() {
            MobileSignatureClient.SignatureServiceStub.getDigestAlgRequest inValue = new MobileSignatureClient.SignatureServiceStub.getDigestAlgRequest();
            inValue.Body = new MobileSignatureClient.SignatureServiceStub.getDigestAlgRequestBody();
            MobileSignatureClient.SignatureServiceStub.getDigestAlgResponse retVal = ((MobileSignatureClient.SignatureServiceStub.Service1Soap)(this)).getDigestAlg(inValue);
            return retVal.Body.getDigestAlgResult;
        }
    }
}